# NumPy 

### NumPy Overview

- general-purpose array-processing Python library.
- Supports the creation and manipulation of n-dimensional arrays.
- Abbreviation for "Numerical Python."
- Developed by Travis Olliphant in 2005.
- Created to overcome the constraints of traditional Python lists for numerical computing.
- Essential for data manipulation, machine learning, and scientific research.

### Features of NumPy

- NumPy provides a powerful N-dimensional array object for efficient handling of multi-dimensional data.
- It includes broadcasting capabilities, allowing operations on arrays of different shapes without explicit replication.
- NumPy offers tools for integrating C/C++ and Fortran code, enhancing performance and flexibility.
- The library includes a wide range of mathematical functions, including linear algebra, Fourier transforms, and random number generation.

### Installation
```bash
pip install numpy
```

### Comparison Between NumPy Arrays and Python Lists

- **Data Type Uniformity**: NumPy arrays require all elements to be of the same type, enhancing performance, while Python lists can hold mixed types, which can reduce efficiency.

- **Performance**: NumPy arrays are significantly faster for numerical operations due to optimized memory usage, whereas Python lists are slower due to more overhead.

- **Functionality**: NumPy offers extensive mathematical functions and supports operations like broadcasting, while Python lists have limited functionality for complex computations.

- **Memory Efficiency**: NumPy arrays are more memory efficient, especially for large datasets, because they use fixed data types, while lists incur additional overhead.

- **Multidimensional Support**: NumPy natively supports multi-dimensional arrays, making complex manipulations easier, while Python lists can be nested but lack performance.

- **Ease of Use**: NumPy requires familiarity with its syntax and functions for scientific tasks, while Python lists are simpler for basic programming needs.


### NumPy Array Creation

- **Using Built-in Functions**:
  - Zeros: `np.zeros((2, 3))` → Creates a 2x3 array of zeros.
  - Ones: `np.ones((2, 3))` → Creates a 2x3 array of ones.
  - Empty: `np.empty((2, 3))` → Creates a 2x3 array with uninitialized data.
  - Range: `np.arange(10)` → Creates an array with values from 0 to 9.
  - Linspace: `np.linspace(0, 1, 5)` → Creates 5 equally spaced values between 0 and 1.
  
- **From Lists and Tuples**:
  - List: `np.array([1, 2, 3])` → Creates a NumPy array from a Python list.
  - Tuple: `np.array((4, 5, 6))` → Creates a NumPy array from a Python tuple.

- **Arange Method**:
  - `np.arange(start, stop, step)` → Creates an array with evenly spaced values within a specified range.
  
- **Identity Matrix**:
  - `np.eye(n)` → Creates an n x n identity matrix.

- **Full Array**:
  - `np.full(shape, fill_value)` → Creates an array filled with a specified value.

- **Meshgrid Function**:
  - `np.meshgrid(x, y)` → Generates coordinate matrices from coordinate vectors.

In [3]:
### From a List or tuple

import numpy as np
arr_from_list = np.array([1, 2, 3])
arr_from_tuple = np.array((4, 5, 6))
print(arr_from_list)
print(arr_from_tuple)

[1 2 3]
[4 5 6]


In [11]:
### The arange Method

range_array = np.arange(10)
print(range_array)
array = np.arange(0, 20, 5)  #Example with start, stop, and step
print(array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15]


In [13]:
# Zeros
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Ones
ones_array = np.ones((2, 3))
print("\nOnes Array:\n", ones_array)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Empty
empty_array = np.empty((2, 2))
print("\nEmpty Array:\n", empty_array)


Empty Array:
 [[0.25 0.5 ]
 [0.75 1.  ]]


The np.empty() function in NumPy is used to create an array without initializing its values. This means that the array is allocated in memory, but the contents are not set to any specific value, leading to potentially unpredictable values depending on the state of the memory at that time.



In [21]:
# Linspace
linspace_array = np.linspace(0, 1, 5)
print("\nLinspace Array (5 values between 0 and 1):\n", linspace_array)


Linspace Array (5 values between 0 and 1):
 [0.   0.25 0.5  0.75 1.  ]


np.linspace(): Generates a specified number of evenly spaced values over a defined interval. It is particularly useful for creating arrays with a fixed number of points between two endpoints.

np.arange(): Generates values within a specified range with a defined step size. It's useful for creating sequences where you specify the increment between values.

In [22]:
# Identity Matrix
identity_matrix = np.eye(3)  # 3x3 identity matrix
print("\nIdentity Matrix (3x3):\n", identity_matrix)


Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Full Array
full_array = np.full((2, 3), 7)  # 2x3 array filled with 7
print(full_array)

[[7 7 7]
 [7 7 7]]


### Meshgrid Function

The `np.meshgrid()` function in NumPy is used to create coordinate matrices (grids) from two or more coordinate vectors. This is particularly useful in scenarios where you want to evaluate functions over a grid of values, such as in 3D plotting or surface generation.

### How It Works

- **Input Vectors**: `np.meshgrid()` takes one or more 1D arrays (coordinate vectors) as input.
- **Output Grids**: It returns arrays that represent the coordinates of a grid. Each output array corresponds to one of the input coordinate vectors, and the shape of the output arrays matches the grid formed by the input vectors.


In [27]:
# Meshgrid Function
x = np.array([1, 2, 3])
y = np.array([1, 2])
X, Y = np.meshgrid(x, y)
print("\nMeshgrid X:\n", X)
print("\nMeshgrid Y:\n", Y)


Meshgrid X:
 [[1 2 3]
 [1 2 3]]

Meshgrid Y:
 [[1 1 1]
 [2 2 2]]


### Array Properties in NumPy

NumPy arrays come with several properties that provide useful information about the array. Here are some key properties:

- **Shape**: 
  - `arr.shape` → Returns the dimensions of the array as a tuple. For example, a 2x3 array would return `(2, 3)`.

- **Size**: 
  - `arr.size` → Returns the total number of elements in the array. For a 2x3 array, this would return `6`.

- **Data Type**: 
  - `arr.dtype` → Returns the data type of the elements in the array. Common types include `int32`, `float64`, and `object`.

- **Number of Dimensions**: 
  - `arr.ndim` → Returns the number of dimensions (axes) of the array. For example, a 2D array would return `2`.

- **Item Size**: 
  - `arr.itemsize` → Returns the size (in bytes) of each element in the array. This is useful for understanding memory usage. For instance, an array of `float64` type would have an item size of `8` bytes.

- **Data Buffer**: 
  - `arr.data` → Returns the buffer containing the actual elements of the array. This is a low-level property that is rarely used directly by most users.

- **Base**: 
  - `arr.base` → If the array is a view (not a copy) of another array, this property returns the base array. If it is a standalone array, it returns `None`.

- **Strides**: 
  - `arr.strides` → Returns a tuple indicating the number of bytes that need to be skipped in memory to move to the next position along each dimension. This is useful for understanding how the array is stored in memory.

- **Flags**: 
  - `arr.flags` → Returns information about the memory layout and properties of the array, such as whether the array is contiguous in memory, whether it is writable, and other attributes.


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)

Array:
 [[1 2 3]
 [4 5 6]]


In [29]:
# Shape
print("\nShape of the array:", arr.shape)


Shape of the array: (2, 3)


In [30]:
# Size
print("Total number of elements:", arr.size) 

Total number of elements: 6


- In NumPy, dtype (short for "data type") is a fundamental concept that defines the type of elements in a NumPy array. 
- It specifies how the data is stored in memory and what kind of operations can be performed on it. Understanding dtype is essential for effective memory management and performance optimization in numerical computations.
- If you don't specify a dtype, NumPy will infer the data type from the input data. For example, if you create an array of integers, it will default to an integer type.
- You can change the dtype of an existing array using the astype() method

Types of Data:

1. Integers: np.int8, np.int16, np.int32, np.int64 (different sizes of integers).
2. Unsigned Integers: np.uint8, np.uint16, np.uint32, np.uint64.
3. Floating Point Numbers: np.float16, np.float32, np.float64 (different sizes of floating-point numbers).
4. Complex Numbers: np.complex64, np.complex128.
5. Booleans: np.bool_ (representing True/False).
6. Strings: np.str_ or np.bytes_ (for text data).
7. Objects: np.object_ (for generic Python objects).



In [39]:
### Setting the dtype:

arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype) 
print(arr)

float32
[1. 2. 3.]


In [31]:
# Data Type
print("Data type of array elements:", arr.dtype) 

Data type of array elements: int64


In [32]:
# Number of Dimensions
print("Number of dimensions:", arr.ndim)

Number of dimensions: 2


In [33]:
# Item Size
print("Size of each element in bytes:", arr.itemsize)

Size of each element in bytes: 8


In [34]:
# Data Buffer
print("Data buffer:", arr.data) 

Data buffer: <memory at 0x7f15d00d0ee0>


In [35]:
# Base Array
print("Base array:", arr.base) 

Base array: None


In [36]:
# Strides
print("Strides:", arr.strides) 

Strides: (24, 8)


In [37]:
# Flags
print("Array flags:\n", arr.flags)

Array flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



Structured Data Types:

NumPy also supports structured arrays, which allow you to create arrays with complex data types. This means you can have arrays that contain different types of data in each element, similar to records in a database.

In [42]:
dtype = np.dtype([('name', 'U10'), ('age', 'i4')])
structured_array = np.array([('abcd', 25), ('qwer', 30)], dtype=dtype)
print(structured_array)

[('abcd', 25) ('qwer', 30)]


## Array Indexing and slicing Operations
- Indexing: access specific elements of an array
1. *Basic Indexing*
is straightforward. It follows zero-based indexing, so `arr[0]` accesses the first element.
2. *Slicing*: allows you to access a subset of an array. It follows the `start:stop:step` syntax.
3. *Boolean Indexing*: filters elements based on a condition.
4. *Fancy Indexing*: allows selection of specific indices in an arbitrary order. You can use lists or arrays of indices.
5. Ellipsis: useful for skipping unspecified dimensions. It’s particularly helpful for higher-dimensional arrays.


In [68]:
### Basic Indexing: 1D Array:

arr = np.array([10, 20, 30, 40])
print(arr[2])
print(arr[-1])    

30
40


In [71]:
### Basic Indexing: 2D Array:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2])
print(arr[0])  
print(arr[1])  
print(arr[2])  
print(arr[2,1])

6
[1 2 3]
[4 5 6]
[7 8 9]
8


In [78]:
### Slicing: 1D Array:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])   
print(arr[:-3])    
print(arr[-2:])  
print(arr[-3:])    
print(arr[-3])    
print(arr[::2]) 
print(arr[::3]) 
print(arr[::5])

[20 30 40]
[10 20 30]
[10 20]
[40 50]
[30 40 50]
30
[10 30 50]
[10 40]
[10]


In [79]:
print(arr[-2:])  

[40 50]


In [83]:
### Slicing: 2D Array:*
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
print(arr[1:3])  #  (rows 1 and 2)

[[4 5 6]
 [7 8 9]]


In [86]:
print(arr[:, 2])

[3 6 9]


In [62]:
print(arr[0:2, 1:])  # (first two rows, last two columns)

array([1])

In [90]:
print(arr[:, ::3])  

[[1]
 [4]
 [7]]


In [91]:
print(arr[-2:, -2:]) 

[[5 6]
 [8 9]]


In [92]:
#  Reverse the order of columns
print(arr[:, ::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [94]:
### Boolean Indexing 1D Array:

arr = np.array([1, 2, 3, 4, 5])
arr[arr < 3] 

array([1, 2])

In [95]:
### Boolean Indexing 2D Array:

arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[arr % 2 == 0]  

array([2, 4, 6])

In [97]:
arr[arr > 3] 

array([4, 5, 6])