### Array Manipulations in NumPy
allows you to modify the shape, size, and contents of arrays. 

1. **Reshaping Arrays**
- **`np.reshape(array, new_shape)`**: Changes the shape of an array without changing its data.

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))  
print(reshaped)

[[1 2 3]
 [4 5 6]]


2. **Flattening Arrays**
- **`array.flatten()`**: Returns a copy of the array collapsed into one dimension.
- **`array.ravel()`**: Returns a flattened array as well but returns a view if possible.

In [8]:
reshaped.flatten()

array([1, 2, 3, 4, 5, 6])

In [9]:
reshaped.ravel()

array([1, 2, 3, 4, 5, 6])

3. **Transposing Arrays**
- **`array.T`**: Returns the transposed version of an array (swaps rows and columns).

In [10]:
reshaped.T

array([[1, 4],
       [2, 5],
       [3, 6]])

6. **Concatenation and Stacking**
- **`np.concatenate((a1, a2), axis)`**: Joins two or more arrays along a specified axis.
- **`np.vstack((a1, a2))`**: Stacks arrays vertically (row-wise).
- **`np.hstack((a1, a2))`**: Stacks arrays horizontally (column-wise).

In [15]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
np.concatenate((arr1, arr2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

axis=0: Concatenates the arrays vertically (adds rows).

axis=1: Concatenates the arrays horizontally (adds columns).

In [17]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

7. **Splitting Arrays**
- **`np.split(array, indices_or_sections)`**: Splits an array into multiple sub-arrays.
- **`np.hsplit(array, indices)`**: Splits an array horizontally.
- **`np.vsplit(array, indices)`**: Splits an array vertically.

In [20]:
np.split(arr, 3) 

[array([1, 2]), array([3, 4]), array([5, 6])]

8. **Adding and Removing Elements**
- **`np.append(array, values)`**: Appends values to the end of an array.
- **`np.delete(array, index)`**: Removes elements from an array at specified indices.
- **`np.insert(array, index, values)`**: Inserts values at specified indices.

In [24]:
arr3 = np.array([1,2,3,4])
print(arr3)

[1 2 3 4]


In [29]:
np.append(arr3, [7, 8])

array([1, 2, 3, 4, 7, 8])

In [30]:
np.delete(arr3, 2)

array([1, 2, 4])

In [31]:
np.insert(arr, 1, 9)

array([1, 9, 2, 3, 4, 5, 6])

9. **Broadcasting**
- Allows operations on arrays of different shapes. NumPy automatically expands the smaller array across the larger array.

In [33]:
arr5 = np.array([1, 2, 3])
arr6 = np.array([[1], [2], [3]])
arr5 + arr6

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])