### Array Operations in NumPy


 1. **Element-wise Operations**
Element-wise operations allow you to perform mathematical operations on each element of an array.

In [1]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                  [10, 11, 12]])

In [2]:
# Element-wise addition
arr1 + arr2 

array([[ 8, 10, 12],
       [14, 16, 18]])

In [3]:
# Element-wise subtraction
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [4]:
# Element-wise multiplication
arr1 * arr2 

array([[ 7, 16, 27],
       [40, 55, 72]])

In [5]:
# Element-wise division
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [6]:
# Element-wise modulus
arr1 % arr2 

array([[1, 2, 3],
       [4, 5, 6]])

2. **Aggregation Functions**
Aggregation functions compute a single value from multiple elements in the array.

**Common Functions**:
- **`np.sum(arr)`**: Returns the sum of all elements.
- **`np.mean(arr)`**: Returns the mean of elements.
- **`np.max(arr)`**: Returns the maximum value.
- **`np.min(arr)`**: Returns the minimum value.

In [7]:
np.sum(arr1)

21

In [8]:
np.mean(arr1)

3.5

In [9]:
np.max(arr1)

6

In [10]:
np.min(arr1)

1

###  Random Number Generation in NumPy

NumPy provides a powerful module, `numpy.random`, for generating random numbers and performing random sampling. 

#### 1. **Generating Random Numbers**

- **Uniform Distribution**: Generate random numbers uniformly between 0 and 1.
- **Normal Distribution**: Generate random numbers from a normal (Gaussian) distribution.
- **Random Integers**: Generate random integers within a specified range.

In [12]:
### Uniform Distribution.
np.random.rand(3)  # Generates 3 random numbers

array([0.04695967, 0.70987391, 0.13868472])

In [14]:
### Normal Distribution: 
np.random.randn(3)  

array([-1.07650885, -1.58600066,  0.8909384 ])

In [15]:
### Random Integers:
np.random.randint(low=0, high=10, size=5)  # Generates 5 random integers between 0 and 9

array([5, 6, 8, 0, 9])

#### 2. **Random Sampling**

- **Choice Function**: Randomly sample elements from an array.
- **Shuffle Function**: Shuffle the elements of an array in place.

In [24]:
array = np.array([1, 2, 3, 4, 5])
np.random.choice(array, size=3, replace=False) 


array([4, 5, 2])

In [27]:
np.random.shuffle(array)

In [28]:
array

array([2, 3, 1, 4, 5])

#### 3. **Setting Seed for Reproducibility**

To ensure that the random numbers generated are reproducible, you can set a seed using `np.random.seed()`

In [29]:
np.random.seed(42)

In [32]:
np.random.rand(3)

array([0.05808361, 0.86617615, 0.60111501])

In [33]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 2 5]
 [4 1 7]]
(2, 3)


In [34]:
arr4 = np.random.randint(0,10,(3,3))
arr5 = np.random.randint(10,20,(3,3))